In [1]:
import numpy as np

# Basic

In [2]:
a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
## dim
print('dim: ', a.ndim)
## shape
print('shape: ', a.shape)
## size
print('size: ', a.size)
## type
print('type: ', a.dtype)

dim:  1
shape:  (3,)
size:  3
type:  int32


In [4]:
b = np.array([[1,2,3], [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
## dim
print('dim: ', b.ndim)
## shape
print('shape: ', b.shape)
## size
print('size: ', b.size)
## type
print('type: ', b.dtype)

dim:  2
shape:  (2, 3)
size:  6
type:  int32


# Arithmetic & Math

In [6]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a*b)

[5 7 9]
[ 4 10 18]


In [7]:
print(a.shape, b.shape)

(3,) (3,)


In [8]:
c = np.array([2,3])
print(c.shape)

(2,)


In [9]:
a + c

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [10]:
a += 3 # a = a + c

In [11]:
a

array([4, 5, 6])

In [12]:
a *=2

In [13]:
a

array([ 8, 10, 12])

In [14]:
a -= 2

In [15]:
a

array([ 6,  8, 10])

In [16]:
np.pi

3.141592653589793

In [17]:
np.e

2.718281828459045

In [18]:
a = np.array([1,2,3])
print('log: ',np.log(a))
print('exp: ',np.exp(a))
print('sin: ',np.sin(np.pi))

log:  [0.         0.69314718 1.09861229]
exp:  [ 2.71828183  7.3890561  20.08553692]
sin:  1.2246467991473532e-16


# Get Specific Elements

In [19]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
## [start_id:end_id:stepsize]

In [21]:
a[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
a[:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [23]:
a[2:8]

array([2, 3, 4, 5, 6, 7])

In [24]:
a[::2]

array([0, 2, 4, 6, 8])

In [25]:
a[1:8:2]

array([1, 3, 5, 7])

In [26]:
a = np.array( [[1,2,3,4], [5,6,7,8], [9, 10, 11, 12]] )
print('a: \n', a)
print('ashape', a.shape)

a: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
ashape (3, 4)


In [27]:
a[1, 2]

7

In [28]:
a[:, 2]

array([ 3,  7, 11])

In [29]:
a[:, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [30]:
a[::2, 1:3]

array([[ 2,  3],
       [10, 11]])

In [31]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
a[::2, 1:3] = np.array([[0,1], [2,3]])
a

array([[ 1,  0,  1,  4],
       [ 5,  6,  7,  8],
       [ 9,  2,  3, 12]])

In [33]:
a[::2, 1:3] = 10
a

array([[ 1, 10, 10,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 10, 12]])

In [34]:
a > 5

array([[False,  True,  True, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [35]:
a[a > 5]

array([10, 10,  6,  7,  8,  9, 10, 10, 12])

In [36]:
a[a%2==0]

array([10, 10,  4,  6,  8, 10, 10, 12])

# Initialization

In [37]:
a = np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [38]:
a = np.full((3,4,5), 5)
a.shape

(3, 4, 5)

In [39]:
b = np.full(a.shape, 10)
b.shape

(3, 4, 5)

In [40]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
## 0 - 1
a = np.random.rand(2,3)
a.shape

(2, 3)

In [42]:
## random integer
a = np.random.randint(0, 3, (3,2))
a

array([[2, 1],
       [1, 1],
       [0, 2]])

In [43]:
## normal distribution
a = np.random.normal(0, 1, (3,2,2))
a

array([[[-0.02779528, -0.54826565],
        [ 1.01851515, -0.4758281 ]],

       [[-0.81429588,  0.94918225],
        [ 1.10245798,  0.36156222]],

       [[-0.51667203,  1.47334313],
        [-0.9307967 , -0.19497126]]])

In [44]:
a = np.arange(0,100 , 20)
a

array([ 0, 20, 40, 60, 80])

In [45]:
a = np.linspace(0, 100, 21)
a

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

# Quiz

In [46]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print('a\n', a)
print('a.shape', a.shape)

a
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
a.shape (4, 4)


In [47]:
a[:,0]

array([ 1,  5,  9, 13])

In [48]:
a[2,:]

array([ 9, 10, 11, 12])

In [49]:
a[1:3,1:3]

array([[ 6,  7],
       [10, 11]])