In [1]:
import numpy as np

# Stats

In [2]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
a.max()

5

In [4]:
a.min()

1

In [5]:
a.sum()

15

In [6]:
a.mean()

3.0

In [7]:
a.std()

1.4142135623730951

In [8]:
a = np.array([[1,3,5],[6,4,2]])
a

array([[1, 3, 5],
       [6, 4, 2]])

In [9]:
a.sum()

21

In [10]:
a.shape

(2, 3)

In [11]:
a.sum(axis = 1)

array([ 9, 12])

# Vector & Matrix

In [12]:
## dot product
a = np.array([1,2,3])
b = np.array([2,4,6])
np.dot(a, b)

28

In [13]:
a * b

array([ 2,  8, 18])

In [14]:
## matrix multiplicationi
a = np.ones((3,2))
b = np.ones((2,4))
print(a)
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
c = np.matmul(a, b)
c.shape

(3, 4)

In [16]:
## determinant
I = np.eye(3)
np.linalg.det(I)

1.0

In [17]:
## inverse matrix
a = np.random.normal(0,1,(3,3))
a

array([[-2.39757318,  0.74197586,  0.33948268],
       [-1.58291934,  1.05562932, -0.24057828],
       [-0.44226947,  0.21455758,  1.01109477]])

In [18]:
ainv = np.linalg.inv(a)
ainv

array([[-0.81490044,  0.49330536,  0.39098525],
       [-1.24306484,  1.65610042,  0.81141827],
       [-0.09266847, -0.13564999,  0.98786477]])

In [19]:
np.matmul(a, ainv)

array([[ 1.00000000e+00, -1.23003060e-16, -6.76990537e-17],
       [-9.74704048e-17,  1.00000000e+00, -4.95626908e-17],
       [-7.78159889e-17,  5.88004700e-17,  1.00000000e+00]])

In [20]:
'''
trace
eigenvalues, eigenvectors
pseudo-inverse
norm
etc...
'''

'\ntrace\neigenvalues, eigenvectors\npseudo-inverse\nnorm\netc...\n'

# Load data from file

In [21]:
a = np.loadtxt('test.csv', delimiter = ',')
a

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.],
       [26., 27., 28., 29., 30.]])

# Others: reshape, stack, repeat etc...

In [22]:
a = np.random.normal(0,1,(3,4))
a

array([[-0.030515  , -1.21517088, -0.31164275,  0.89396362],
       [-1.32623306, -1.07397549, -0.6129996 ,  1.42331394],
       [ 0.28556591,  0.33229509,  0.31546732, -0.51708462]])

In [23]:
a.reshape(12)

array([-0.030515  , -1.21517088, -0.31164275,  0.89396362, -1.32623306,
       -1.07397549, -0.6129996 ,  1.42331394,  0.28556591,  0.33229509,
        0.31546732, -0.51708462])

In [24]:
a.reshape(2,4)

ValueError: cannot reshape array of size 12 into shape (2,4)

In [25]:
a

array([[-0.030515  , -1.21517088, -0.31164275,  0.89396362],
       [-1.32623306, -1.07397549, -0.6129996 ,  1.42331394],
       [ 0.28556591,  0.33229509,  0.31546732, -0.51708462]])

In [26]:
a.shape

(3, 4)

In [27]:
a.T

array([[-0.030515  , -1.32623306,  0.28556591],
       [-1.21517088, -1.07397549,  0.33229509],
       [-0.31164275, -0.6129996 ,  0.31546732],
       [ 0.89396362,  1.42331394, -0.51708462]])

In [28]:
a = np.ones((2,4))
b = np.zeros((2,3))
print(a)
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [29]:
c = np.hstack((a, b))
c

array([[1., 1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0.]])

In [30]:
a = np.ones((3,4,5))
b = np.zeros((3,2,5))

In [31]:
c = np.concatenate((a, b), axis = 1)
print(c.shape)

(3, 6, 5)


In [32]:
a = np.array((1,2,3))
a

array([1, 2, 3])

In [33]:
a.repeat(3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [34]:
np.tile(a, 2)

array([1, 2, 3, 1, 2, 3])

In [35]:
np.tile(a, (2,2))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

# Quiz

In [36]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2],[3,4],[5,6]])
c = np.array([[1,2,3]])
print('--a--')
print(a)
print('shape: ',a.shape)

print('--b--')
print(b)
print('shape: ', b.shape)

print('--c--')
print(c)
print('shape: ',c.shape)
'''
(1)aの転置を求めよ
(2)aとbの行列の積は？
(3)aのshapeを(6,1)に変更せよ
(4)aとcをnp.vstack, np.hstackしたらそれぞれどうなるか
'''

--a--
[[1 2 3]
 [4 5 6]]
shape:  (2, 3)
--b--
[[1 2]
 [3 4]
 [5 6]]
shape:  (3, 2)
--c--
[[1 2 3]]
shape:  (1, 3)


'\n(1)aの転置を求めよ\n(2)aとbの行列の積は？\n(3)aのshapeを(6,1)に変更せよ\n(4)aとcをnp.vstack, np.hstackしたらそれぞれどうなるか\n'

In [37]:
## (1)
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [38]:
## (2)
np.matmul(a,b)

array([[22, 28],
       [49, 64]])

In [39]:
## (3)
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [40]:
## (4)
np.vstack((a,c))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [41]:
## (4)
np.hstack((a,c))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1