In [1]:
import numpy as np

# ブロードキャスト

# Rule 1

In [2]:
'''
対象の配列の中で次元数が一番大きな配列より次元数の小さな配列は全てshapeの先頭に1を入れる
'''

'\n対象の配列の中で次元数が一番大きな配列より次元数の小さな配列は全てshapeの先頭に1を入れる\n'

In [3]:
a = np.ones((1,3,2))
b = np.ones((3,2))
c = a + b

In [4]:
print(a.ndim)
print(b.ndim)

3
2


In [5]:
a

array([[[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [6]:
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [7]:
c.shape

(1, 3, 2)

# Rule 2

In [8]:
'''
出力される配列の各次元の要素数（shape）は対象となる配列の各次元の要素数のなかで最大のものになる
'''

'\n出力される配列の各次元の要素数（shape）は対象となる配列の各次元の要素数のなかで最大のものになる\n'

In [9]:
a = np.ones((3,2,1))
b = np.ones((1,2,3))
c = a + b

In [10]:
c.shape

(3, 2, 3)

# Rule 3

In [11]:
'''
配列の各次元の要素数が一致しているか，1のとき，それらの配列は計算することができる
'''

'\n配列の各次元の要素数が一致しているか，1のとき，それらの配列は計算することができる\n'

In [12]:
a = np.ones((1,3,4,1))
b = np.ones((3,1,4,5))
c = a + b

In [13]:
c.shape

(3, 3, 4, 5)

In [14]:
a = np.ones((3,3,4))
b = np.ones((3,3,2))
c = a + b

ValueError: operands could not be broadcast together with shapes (3,3,4) (3,3,2) 

# Rule 4

In [15]:
'''
次元の要素数が1でブロードキャストがなされる場合，同じ値を繰り返す
'''

'\n次元の要素数が1でブロードキャストがなされる場合，同じ値を繰り返す\n'

In [16]:
a = np.array([[1,2],[3,4]])
b = np.array([[5, 6]])

In [17]:
a.shape

(2, 2)

In [18]:
b.shape

(1, 2)

In [19]:
a + b

array([[ 6,  8],
       [ 8, 10]])

# Quiz

In [20]:
a = np.ones((2, 2, 3))
b = np.ones((3, 2))
 
c = a + b

ValueError: operands could not be broadcast together with shapes (2,2,3) (3,2) 

In [21]:
a = np.ones((2, 2, 3))
b = np.ones((3, 3))
 
c = a + b

ValueError: operands could not be broadcast together with shapes (2,2,3) (3,3) 

In [22]:
a = np.ones((2, 2, 3))
b = np.ones((3))
 
c = a + b

In [23]:
a = np.ones((2, 2, 3))
b = np.ones((2, 3))
 
c = a + b

In [24]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5], [6]])
 
c = a + b